name: flutter_master_detail_example
description: An adaptive master-detail example for Flutter.
publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
